# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='IDJugador',
            field=models.IntegerField(),
        ),
    ]
