# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDJugadorUno', models.CharField(max_length=50)),
                ('IDJugadorDOs', models.CharField(max_length=50)),
                ('CantFichasLinea', models.IntegerField()),
                ('TamannoTablero', models.IntegerField()),
                ('IDGanador', models.CharField(max_length=50)),
                ('EstadoTablaFinal', models.CharField(max_length=1000)),
                ('Turno', models.CharField(max_length=10)),
                ('Estado', models.CharField(max_length=10)),
                ('ListaMovimientos', models.CharField(max_length=1000)),
            ],
        ),
    ]
