# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='IDJugadorDOs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partida',
            name='IDJugadorUno',
            field=models.IntegerField(),
        ),
    ]
