# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Partida', '0002_auto_20170915_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partida',
            old_name='EstadoTablaFinal',
            new_name='JugadasP1',
        ),
        migrations.RenameField(
            model_name='partida',
            old_name='ListaMovimientos',
            new_name='JugadasP2',
        ),
    ]
